version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER} # ПЕРЕМЕННАЯ ИЗ .ENV
      POSTGRES_PASSWORD: ${DB_PASS} # ПЕРЕМЕННАЯ ИЗ .ENV
      POSTGRES_DB: ${DB_NAME} # ПЕРЕМЕННАЯ ИЗ .ENV
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
