"""Create Strapon Table

Revision ID: c0538588aa9d
Revises: dc1ac86114c6
Create Date: 2025-01-25 18:24:29.009948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0538588aa9d'
down_revision: Union[str, None] = 'dc1ac86114c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dildo',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dildo_email'), 'dildo', ['email'], unique=True)
    op.create_index(op.f('ix_dildo_id'), 'dildo', ['id'], unique=False)
    op.create_index(op.f('ix_dildo_name'), 'dildo', ['name'], unique=False)
    op.create_table('strapon',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strapon_email'), 'strapon', ['email'], unique=True)
    op.create_index(op.f('ix_strapon_id'), 'strapon', ['id'], unique=False)
    op.create_index(op.f('ix_strapon_name'), 'strapon', ['name'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_strapon_name'), table_name='strapon')
    op.drop_index(op.f('ix_strapon_id'), table_name='strapon')
    op.drop_index(op.f('ix_strapon_email'), table_name='strapon')
    op.drop_table('strapon')
    op.drop_index(op.f('ix_dildo_name'), table_name='dildo')
    op.drop_index(op.f('ix_dildo_id'), table_name='dildo')
    op.drop_index(op.f('ix_dildo_email'), table_name='dildo')
    op.drop_table('dildo')
    # ### end Alembic commands ###
