"""Create Vibrator Table

Revision ID: aaf1496d9225
Revises: c0538588aa9d
Create Date: 2025-01-25 18:29:06.789829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf1496d9225'
down_revision: Union[str, None] = 'c0538588aa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibrator',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vibrator_email'), 'vibrator', ['email'], unique=True)
    op.create_index(op.f('ix_vibrator_id'), 'vibrator', ['id'], unique=False)
    op.create_index(op.f('ix_vibrator_name'), 'vibrator', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vibrator_name'), table_name='vibrator')
    op.drop_index(op.f('ix_vibrator_id'), table_name='vibrator')
    op.drop_index(op.f('ix_vibrator_email'), table_name='vibrator')
    op.drop_table('vibrator')
    # ### end Alembic commands ###
